print("- Main Menu -")
print("1. List all accounts")
print("2. View an account balance")
print("3. Deposit")
print("4. Withdraw")
print("5. Transfer")
print("6. Add account")
print("7. Remove account")
print("8. Save accounts to file")
print("9. Quit")
